when:
  - event: [tag, push, release, deployment, cron, manual]
    branch: [main]

steps:
  - name: build
    image: node:23.11
    environment:
      # secrets must be set in Woodpecker configuration
      UMAMI_DOMAIN:
        from_secret: umami_domain
      UMAMI_ID:
        from_secret: umami_id
    commands:
      - npm ci
      - npm run build

  - name: upload
    image: node:23.11
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
    commands:
      - npx --yes dxfl deploy guerilla.studio _site/ --yes
